#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
const version = packageJson.version;

if (typeof version !== "string" || version.length === 0) {
  throw new Error("package.json version must be a non-empty string");
}

await writeFile(
  path.join(root, "packages", "core", "src", "version.ts"),
  `// Generated by scripts/generate-version.mjs from package.json.\nexport const CRUCIBLE_VERSION = ${JSON.stringify(version)};\n`,
);
